services:

  api:
    image: node:24.11-alpine
    container_name: iziclub_api
    working_dir: /app
    volumes:
      - .:/app
      - api_node_modules:/app/node_modules
    env_file:
      - .env
    command: >
      sh -c "npm install && npm run dev"
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    networks:
      - adonis_net
  postgres:
    image: postgres:18.0-alpine3.22
    container_name: iziclub_postgres
    restart: always
    environment:
      POSTGRES_USER: iziclub
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: iziclub_db
      TZ: "Europe/Paris"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - adonis_net
      
volumes:
  postgres_data:
  api_node_modules:

networks:
  adonis_net:
    driver: bridge
