name: CI Pipeline

on:
  push:
    branches: [feature/*, feature/**/*]
  pull_request:
    branches: [develop, main]

defaults:
  run:
    working-directory: ./monorepo

jobs:
   run-tests:
    runs-on: ubuntu-latest
    name: Run tests in monorepo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Configure AdonisJS environment
        working-directory: ./monorepo/apps/api
        run: |
          echo "NODE_ENV=test" >> .env
          echo "PORT=3333" >> .env
          echo "APP_KEY=secret_key" >> .env
          echo "HOST=0.0.0.0" >> .env
          echo "LOG_LEVEL=debug" >> .env

      - name: Run tests
        run: pnpm turbo run test  --cache-dir=.turbo
   
   build-api:
    runs-on: ubuntu-latest
    needs: run-tests
    name: Build api project (adonisjs)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build project
        run: pnpm run build --filter api --cache-dir=.turbo
            
   build-web:
    runs-on: ubuntu-latest
    needs: run-tests
    name: Build web project (nextjs)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build project
        run: pnpm run build --filter web --cache-dir=.turbo

   